MG5_MODULES="cuda/12.6 gcc/13.2.0" #  intel mkl python/3.12.1"

MG5_HOME=${SLURM_SUBMIT_DIR}
MG5_USER=${SLURM_JOB_USER}
MG5_GPU_NAME=CUDA
MG5_GPU_ARCH=90
MG5_PROC=pp_ttx_gpu

MG5_SLURM_DIR=slurm-${SLURM_JOBID}
MG5_OUTP_DIR=/gpfs/projects/${SLURM_JOB_ACCOUNT}/MG5/${MG5_PROC_TAG}/${MG5_SLURM_DIR}
MG5_WORK_DIR=${TMPDIR}/${MG5_SLURM_DIR}

MG5_EVAL1="NVIDIA_VISIBLE_DEVICES=$(nvidia-smi -L | tr -d \) | awk '{print $NF'} | tr \\n , | sed s/\,$//)"
MG5_EVAL2="unset CUDA_VISIBLE_DEVICES"
MG5_EVAL3="unset ROCR_VISIBLE_DEVICES"
MG5_EVAL_LIST="${MG5_EVAL1} ${MG5_EVAL2} ${MG5_EVAL3}"

MG5_GPUS_VAR=NVIDIA_VISIBLE_DEVICES
