MG5_GPU_MODULE=
MG5_GPU_VERSION=

MG5_GCC_MODULE=
MG5_GCC_VERSION=

MG5_PYTHON_MODULE=cray-python
MG5_PYTHON_VERSION=3.11.7

MG5_HOME=${SLURM_SUBMIT_DIR}
MG5_USER=${SLURM_JOB_USER}
MG5_GPU_NAME=HIP
MG5_GPU_ARCH=gfx90a
MG5_PROC=pp_ttx_gpu
