MG5_MODULES="cray-python/3.11.7"

MG5_HOME=/projappl/project_465002230/${USER}
MG5_USER=${SLURM_JOB_USER}
MG5_GPU_NAME=HIP
MG5_GPU_ARCH=gfx90a
MG5_PROC=pp_ttx_gpu

MG5_SLURM_DIR=slurm-${SLURM_JOBID}
MG5_OUTP_DIR=/projappl/${SLURM_JOB_ACCOUNT}/MG5/${MG5_PROC_TAG}/${MG5_SLURM_DIR}
MG5_WORK_DIR=${TMPDIR}/${MG5_SLURM_DIR}
