MG5_MODULES=

MG5_HOME=/shared/roiser/
MG5_USER=${USER}
MG5_PROC=pp_ttx_gpu

MG5_SLURM_DIR=$(shuf -i 1-100000000 -n 1)
SLURM_JOBID=${MG5_SLURM_DIR}
MG5_OUTP_DIR=/shared/roiser/MG5/${MG5_PROC_TAG}/${MG5_SLURM_DIR}
MG5_WORK_DIR=${TMPDIR}/${MG5_USER}/${MG5_SLURM_DIR}
